"""
Telemetry module for ai-lib-python.

Provides structured logging, metrics collection, distributed tracing,
health monitoring, and user feedback collection.
"""

from ai_lib_python.telemetry.feedback import (
    ChoiceSelectionFeedback,
    CompositeFeedbackSink,
    ConsoleFeedbackSink,
    CorrectionFeedback,
    FeedbackEvent,
    FeedbackSink,
    FeedbackType,
    InMemoryFeedbackSink,
    NoopFeedbackSink,
    RatingFeedback,
    RegenerateFeedback,
    StopFeedback,
    TextFeedback,
    ThumbsFeedback,
    get_feedback_sink,
    report_feedback,
    set_feedback_sink,
)
from ai_lib_python.telemetry.health import (
    AggregatedHealth,
    HealthChecker,
    HealthCheckResult,
    HealthStatus,
    ProviderHealthTracker,
    get_health_checker,
    get_health_tracker,
)
from ai_lib_python.telemetry.logger import (
    AiLibLogger,
    LogContext,
    LogLevel,
    SensitiveDataMasker,
    clear_log_context,
    get_log_context,
    get_logger,
    set_log_context,
)
from ai_lib_python.telemetry.metrics import (
    HistogramBuckets,
    MetricLabels,
    MetricsCollector,
    MetricSnapshot,
    get_metrics_collector,
    set_metrics_collector,
)
from ai_lib_python.telemetry.tracer import (
    ConsoleExporter,
    InMemoryExporter,
    Span,
    SpanContext,
    SpanExporter,
    SpanKind,
    SpanStatus,
    Tracer,
    get_current_span,
    get_current_span_id,
    get_current_trace_id,
    get_tracer,
    set_tracer,
)

__all__ = [
    # Health
    "AggregatedHealth",
    # Logger
    "AiLibLogger",
    # Feedback
    "ChoiceSelectionFeedback",
    "CompositeFeedbackSink",
    "ConsoleFeedbackSink",
    # Tracer
    "ConsoleExporter",
    "CorrectionFeedback",
    "FeedbackEvent",
    "FeedbackSink",
    "FeedbackType",
    "HealthCheckResult",
    "HealthChecker",
    "HealthStatus",
    "HistogramBuckets",
    "InMemoryExporter",
    "InMemoryFeedbackSink",
    "LogContext",
    "LogLevel",
    # Metrics
    "MetricLabels",
    "MetricSnapshot",
    "MetricsCollector",
    "NoopFeedbackSink",
    "ProviderHealthTracker",
    "RatingFeedback",
    "RegenerateFeedback",
    "SensitiveDataMasker",
    "Span",
    "SpanContext",
    "SpanExporter",
    "SpanKind",
    "SpanStatus",
    "StopFeedback",
    "TextFeedback",
    "ThumbsFeedback",
    "Tracer",
    "clear_log_context",
    "get_current_span",
    "get_current_span_id",
    "get_current_trace_id",
    "get_feedback_sink",
    "get_health_checker",
    "get_health_tracker",
    "get_log_context",
    "get_logger",
    "get_metrics_collector",
    "get_tracer",
    "report_feedback",
    "set_feedback_sink",
    "set_log_context",
    "set_metrics_collector",
    "set_tracer",
]
